# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: "agentcicd"

stages:
  - stage: Stage_A
    displayName: This is Stage A
    jobs:
      - job: Job_A
        displayName: This is Job_A
        steps:
          - script: echo "Stage A Completed"
  - stage: Stage_B
    displayName: This is Stage B
    jobs:
      - job: Job_B
        displayName: This is Job_B
        steps:
          - script: echo "Stage B Completed"
  - stage: Stage_C
    displayName: This is Stage C
    jobs:
      - job: Job_C
        displayName: This is Job_C
        steps:
          - script: echo "Stage C Completed"       