apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-lite
  namespace: youtube-lite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube-lite
  template:
    metadata:
      labels:
        app: youtube-lite
    spec:
      containers:
      - name: youtube-lite
        image: youtube_lite:v4  # Update your image
        ports:
        - containerPort: 80
