apiVersion: v1
kind: Service
metadata:
  name: youtube-lite-service
  namespace: youtube-lite
spec:
  selector:
    app: youtube-lite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
